apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: uptimekumainstances.uptimekuma.example.com
spec:
  group: uptimekuma.example.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required: [subdomain, credentialsSecret]
              properties:
                subdomain:
                  type: string
                  pattern: '^[a-z0-9]([-a-z0-9]*[a-z0-9])?$'
                credentialsSecret:
                  type: string
                replicas:
                  type: integer
                  minimum: 0
            status:
              type: object
              properties:
                deploymentName:
                  type: string
                serviceName:
                  type: string
                ingressName:
                  type: string
                status:
                  type: string
                  enum: [Pending, Running, ScaledToZero, Deleted, Error]
      additionalPrinterColumns:
        - name: Subdomain
          type: string
          jsonPath: .spec.subdomain
        - name: Status
          type: string
          jsonPath: .status.status
  scope: Namespaced
  names:
    plural: uptimekumainstances
    singular: uptimekumainstance
    kind: UptimeKumaInstance
    shortNames:
      - uki