apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-manager-binding
  namespace: {{ .Values.namespace }}
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-backend
  namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: {{ .Release.Name }}-manager
  apiGroup: rbac.authorization.k8s.io