apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-manager
  namespace: {{ .Values.namespace }}
rules:
- apiGroups: ["uptimekuma.example.com"]
  resources: ["uptimekumainstances"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]