name: Build Docker and Helm Chart

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          push: true
          tags: ghcr.io/${{ github.repository }}/backend:${{ github.sha }}

      - name: Run tests
        working-directory: ./backend
        run: |
          npm install
          npm run build
          # Add unit tests here, e.g., npm test

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: '3.10.0'

      - name: Package Helm chart
        run: |
          helm package ./helm/utkaas --destination packaged-helm